# @package _global_
# Training configuration

lr: 0.001        # Learning rate
momentum: 0.9    # Momentum for optimizers that support it
batch_size: 32   # Batch size for training
epochs: 10       # Number of training epochs
